namespace RomDownloader
{
	runtimeclass RomItem
	{
		RomItem();
		RomItem(String Name, String Size, String ImageSrc, Windows.Storage.StorageFile File);

		String Name;
		String Size;
		String ImageSrc;
		Windows.Storage.StorageFile File;
	}
}